#------------------- Packages from composer -------------------#
FROM composer:latest as vendor
WORKDIR /app
COPY composer.json composer.json
COPY composer.lock composer.lock
RUN composer install \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    # --no-dev \
    --prefer-dist
COPY . .
RUN composer dump-autoload

#------------------- Actual container -------------------#
FROM php:8.2-fpm as runner
RUN apt-get update \
    && apt-get install -y build-essential openssl nginx libzip-dev zip 
RUN docker-php-ext-install pdo_mysql mysqli bcmath zip
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
WORKDIR /var/www
RUN chown -R www-data:www-data /var/www  
COPY --from=vendor app/vendor/ ./vendor/
COPY --chown=www-data:www-data . .
RUN ["chmod", "+x", "./docker/post_deploy.sh"]
CMD [ "sh", "./docker/post_deploy.sh" ]
# CMD ["php-fpm"]